spring:
  application:
    name: springsecurity
  datasource:
    url: jdbc:postgresql://localhost:54330/auth_db
    username: root
    password: security123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub
logging:
  level:
    org:
      springframework:
        security=DEBUG: