services:
  redis:
    image: redis:latest
    container_name: security-redis
    ports:
      - "63790:6379"
    restart: always
    volumes:
      - security-redis-data:/data
volumes:
  security-redis-data:
