INSERT INTO tb_permissions (name) VALUES
('MANAGE_USERS'),
('MANAGE_ROLES'),
('VIEW_REPORTS'),
('MANAGE_PERMISSIONS'),
('VIEW_PROFILE'),
('UPDATE_PROFILE'),
('PLACE_ORDER'),
('VIEW_ORDER_HISTORY'),
('CREATE_PRODUCT'),
('UPDATE_PRODUCT'),
('DELETE_PRODUCT'),
('VIEW_ORDERS');
